#!/usr/bin/env bash
#Displays the contents of the file '/etc/passwd'.
#Only displays the username, user ID, and user home directory path for the user

awk '{a[$1" "$9]++} END {for (i in a) print a[i], i}' apache-access.log | sort -rn
