#!/usr/bin/env bash
# Bash script grouping visitors IP and HTTP status code and display the data

awk '{count[$1" "$9]++} END {for (key in count) printf "%d %s\n", count[key], key}' apache-access.log | sort -k1,1nr -k2,2 -k3,3
