#!/usr/bin/env bash
# loops from 1 to 10 and:

#display Best School for the other iteration
#display bad luck for the 4th loop iteration
#display good luck for the other iterations

count=0
while [ $count -lt 10 ]
do
 if [ $count -eg 3 ]
 then
   echo "bad luck"
 elif [ $count -eq 7 ]
 then
  echo "good luck"
 else
  echo "Best School"
 fi
 (( count++ ))
done
