#!/usr/bin/env bash
#loops from 1-10 and:

#displays Best School for the other iterations
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  elif [ $count -eq 7 ]
  then 
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
echo "Best School"
