#!/usr/bin/env bash
# Create the PID file

echo $$ > /var/run/myscript.pid

# Trap signals and define signal handlers
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit 0' SIGTERM

# Display message indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 1
 
done

