#!/usr/bin/env bash

# Create the PID file
echo $$ > /var/run/myscript.pid

# Trap signals and define signal handlers
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Display message indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 1
done

