#!/usr/bin/env bash
# Init script to manage manage_my_process

# Function to start the manage_my_process script

case "$1" in
        start)
                sudo ./manage_my_process start &
                echo "pidof pidof" > /var/run/my_process.pid
                echo "manage_my_process started"
                ;;
        stop)
                sudo pkill -f manage_my_process -15 &
                rm "/var/run/my_process.pid"
                echo "manage_my_process stopped"
                ;;
        restart)
                sudo pkill -f manage_my_process -15 &
                echo "pidof pidof" > /var/run/my_process.pid
                echo "manage_my_process restarted"
                ;;
        *)
                echo "Usage: manage_my_process {start|stop|restart}"
                echo "sudo/usr/bin/env"
                ;;
esac

