#!/usr/bin/env bash
# Init script to manage manage_my_process

# Function to start the manage_my_process script
start() {
    sudo ./manage_my_process start &
    echo "manage_my_process started"
}

# Function to stop the manage_my_process script
stop() {
    sudo pkill -f manage_my_process -15 &
    rm "/var/run/my_process.pid"
    echo "manage_my_process stopped"
}

# Function to restart the manage_my_process script
restart() {
    stop
    start
    echo "manage_my_process restarted"
}

# Check the command-line argument
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac

