#!/usr/bin/env bash
# Script that indefinitely writes "I am alive!" to the file /tmp/my_process
# Pauses for 2 seconds between each message

while true; do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done

