#!/usr/bin/env bash

# Function to start the manage_my_process script
start() {
    # Check if the process is already running
    if [[ -f /var/run/my_process.pid ]]; then
        echo "manage_my_process is already running."
    else
        # Start manage_my_process in the background
        ./manage_my_process &
        PID=$!
        echo $PID > /var/run/my_process.pid
        echo "manage_my_process started"
    fi
}

# Function to stop the manage_my_process script
stop() {
    # Check if the process is running and stop it
    if [[ -f /var/run/my_process.pid ]]; then
        PID=$(cat /var/run/my_process.pid)
        kill "$PID"
        rm /var/run/my_process.pid
        echo

